language: python
before_install:
  - sudo apt-get install libzmq3 libzmq3-dev
install:
  - pip install -r requirements.txt
python:
  - "2.7"
  - "3.3"
  - "3.4"
script:
  - python test.py
  - python setup.py install
